version: '3.9'
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
  redis:
    image: redis:6.2.6-alpine
    restart: always
    ports:
      - 6379:6379
  redis-web:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
     - REDIS_HOSTS=local:redis:6379
    ports:
     - 9080:8081
volumes:
  mongodb-data:
    external: true