version: "3.9"
services:
  mongo:
    image: mongo:5.0.3
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - vulder-search-db:/data/db
  redis:
    image: redis:6.2.6-alpine
    restart: always
    ports:
      - 6379:6379
volumes:
  vulder-search-db:
    external: true