version: '3.9'
services:
  search:
    build: .
    ports:
      - 80:80
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
volumes:
  mongodb-data:
    external: true