version: '3.9'
services:
  search:
    build: .
    ports:
      - 80:80
    restart: always
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081